### ISSUE TITLE
Work if http/https isn't in the URL

### ISSUE THREAD

**Issue by ericwbailey** [danielsmc/structure-exposed#7]
Currently you need to prepend the URL with `http://` or `https://` to get the form to submit. Although this is ~ technically accurate ~, I do think this leads to some UX issues where people are just largely used to things working without it.

Alas, I am too dumb to know how to fix this.

**Comment by danielsmc** [comment]
Probably the easiest fix here would be to add the `novalidate` attribute, at least until more browsers support the `validatebutdontbeadickaboutit` attribute.

**Comment by ericwbailey** [comment]
Looks like `formnovalidate` did the trick!
